Разметка главной и внутренней страниц проекта.
htmlacademy-htmlcss/1418427-technomart-29 pull request #2
Opened 2020-09-14 05:02 UTC by FavorSky23

2020-09-16 08:56 UTC, AleksandrLv requested changes

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +        <h1>ТЕХНОМАРТ</h1>
Это хэдер. Он на всех страницах присутствует. Заголовок h1 везде будет одинаковым, хотя страницы разные. Тут заголовок не нужен

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +      <section class="contacts">
На section делить хэдер тут не очень очевидно. Лучше не использовать семантические теги там, где есть вопрос - а нужны ли они тут. Если везде использовать семантичные теги, то можно сделать хуже

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +      <section class="login">
Это больше на aside похоже, так как можно вынести в любое место сайта и смысл не потеряется

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +    <main class="container">
Вставить классы - это разве в задании есть (я не уверен)? Если нет в задании, то не надо этого делать, потому что увеличивается время проверки задания и сложно проверить всё внимательно, когда очень много всего

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +          <h2>ПОПУЛЯРНЫЕ ТОВАРЫ:</h2>
капсом(uppercase) через стили обычно текст делают

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +              <img src="img" alt="Перфоратор BOSCH BFG 9000">
Лучше всё-таки заглушку вставлять

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +          <button class="button-buy" type="button" name="buy">25500 Р.</button>
Если del используешь, то и ins используй. Правда, я никогда не встречал эти теги

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +            <p>
Зачем в параграф оборачиваешь?

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +          <h4>BOSCH</h4>
Тайтл BOSCH и alt BOSCH. Масло масляное. Здесь я вижу простой список картинок без article и заголовков, возможно, с ссылками, но это не всегда обязательно.

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +        поднимая его на ваш этаж!</p>
Оформляй html код однообразно. Предлагаю так - если в одну строчку помещается, то 
```html
<p>текст</p>
```
иначе
```html
<p>
    Длинный текст
</p>
```

Так проще визуально отделять блоки

2020-09-16 08:56 UTC, AleksandrLv commented on index.html
> +        <h2>Доставка</h2>
В section надо поместить. Заголовок, текст и картинку

2020-09-17 07:33 UTC, AleksandrLv requested changes

2020-09-17 07:33 UTC, AleksandrLv commented on index.html
> +          <a href="#">Каталог</a>
На каталог есть файл. catalog-items.html Переименуй его просто в catalog.html =) Могут придраться на проверке. По хлебным крошкам, по которым ты определял название файла не всегда можно понять, что структура html документа будет отличаться на "Каталог" и "Перфораторы". Поэтому раньше времени не усложняй

2020-09-17 07:33 UTC, AleksandrLv commented on index.html
> +    </section>
Тут лучше div подойдёт. Для section тут слишком разнородная информация

2020-09-17 14:19 UTC, FavorSky23 commented on index.html
> +            <p>
Переписал производителей списком, не оборачивая в <p>.

2020-09-17 18:53 UTC, AleksandrLv requested changes

2020-09-17 18:53 UTC, AleksandrLv commented on catalog.html
> +          <a href="">Каталог</a>
href не нужен

2020-09-17 18:53 UTC, AleksandrLv commented on catalog.html
> +        <a href="">Каталог</a>
href не нужен

2020-09-17 18:53 UTC, AleksandrLv commented on catalog.html
> +        </a>
Почему эта ссылка пустая?

2020-09-17 18:53 UTC, AleksandrLv commented on catalog.html
> +          </p>
Зачем в параграф обернул всё? По моему, тут логичнее img и p друг под другом

2020-09-17 18:53 UTC, AleksandrLv commented on catalog.html
> +    </p>
Это 3 разных параграфа

2020-09-17 18:53 UTC, AleksandrLv commented on catalog.html
> +        <li><a href="">Каталог</a></li>
href не нужен

2020-09-17 23:27 UTC, FavorSky23 commented on catalog.html
> +    </p>
Так принято выделять или так правильнее? 
Вообще лучше параграф с текстом чтобы был в одну строчку или это от ситуации зависит?

2020-09-23 19:11 UTC, AleksandrLv requested changes

2020-09-23 19:11 UTC, AleksandrLv commented on catalog.html
> +          <p>Перфоратор BOSCH BFG 6000</p>
Тут не нужен параграф внутри ссылки

2020-09-25 05:16 UTC, merged