Добавлены классы элементам главной страницы и страницы каталога.
htmlacademy-htmlcss/1418427-technomart-29 pull request #3
Opened 2020-09-28 10:51 UTC by FavorSky23

1. Добавлены классы.
2. В коментариях к стилям на главной задан вопрос.

2020-09-28 19:31 UTC, AleksandrLv commented on index.html
> +  <!-- В лекции было сказано что стили находятся в папке CSS. Вопрос: они должны там изначально находться или мы должны их сами подобрать и туда прописать? -->
Вопросы лучше в комментариях пул реквеста писать, а не в коде.
Если файла нет в репозитории, то надо создать самому и там писать стили

2020-09-29 07:03 UTC, FavorSky23 commented on index.html
> +  <!-- В лекции было сказано что стили находятся в папке CSS. Вопрос: они должны там изначально находться или мы должны их сами подобрать и туда прописать? -->
Если в репозитории есть папка со шрифтами, то мы ее подключаем через css таким образом: 

/*Fonts*/
@font-face {
 font-family: Cuprum;
 src: url(ссылка на папку со шрифтами в локальном репозитории.woff2);
url(ссылка на папку со шрифтами в локальном репозитории.woff);
}

/*Header*/
.header {
font-family: Cuprum; 
}

Правильно я понимаю?

При подключении у меня браузер продолжает показывать что шрифт рендеринга Times New Roman. В чем ошибка ?

2020-10-01 06:48 UTC, AleksandrLv requested changes

2020-10-01 06:48 UTC, AleksandrLv commented on catalog.html
> +  <link rel="stylesheet" href="css/style.css">
Шрифт и здесь надо подключить

2020-10-01 07:05 UTC, AleksandrLv requested changes

2020-10-01 07:05 UTC, AleksandrLv commented on css/style.css
> +.pop-producers div {
Это прям не очень хорошее правило потому что внутри pop-producers может быть несколько тегов div и ко всем применятся одни стили. Ты точно так и задумывал? Лучше назвать этот div каким-нибудь классом

2020-10-01 07:05 UTC, AleksandrLv commented on css/style.css
> +  line-height: 30px;
Ещё в body можно задать `line-height: 1` и тогда не надо прописывать line-height равный размеру шрифта

2020-10-01 09:14 UTC, FavorSky23 commented on css/style.css
> +  font-weight: normal;
Тоесть если стиль Cuprum обычный то добавлять только font-family, а если жирный например то уже прописывать font-weight и font-style, я правильно понимаю ?

2020-10-01 09:16 UTC, FavorSky23 commented on css/style.css
> +  text-decoration: none;
Немножко не додумался😂

2020-10-01 09:16 UTC, AleksandrLv commented on css/style.css
> +  font-weight: normal;
правильно

2020-10-11 07:36 UTC, merged